config/routes.rb
Rails.application.routes.draw do
  resources :tobuys
  get 'sessions/new'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :items
  resources :categories
  resources :explos
  resources :users
  resources :adoptions 
  resources :accidents
  resources :wydanies
  resources :subcategories
  resources :subsubcategories
  resources :statuses
  resources :locations
  resources :units
  resources :wzs
  resources :lives
  resources :actions
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'acc' => 'wydanies#accepted'
  get 'ac' => 'accidents#ac'
  get 'all' => 'wydanies#all'
  
  
  root'home#index'

end

app/models/accident.rb
class Accident < ActiveRecord::Base
  belongs_to :location
  belongs_to :user
  belongs_to :status
  has_many :action

  validates :location_id, presence: true

end

app/models/action.rb
class Action < ActiveRecord::Base
  belongs_to :user
  belongs_to :accident
  belongs_to :status
  
#    validates :description, :status_id, presence: true

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable  

  has_many :wzs

end

app/models/adoption.rb
class Adoption < ActiveRecord::Base
  belongs_to :user
  belongs_to :explo
  belongs_to :unit
  
  validates :quantity, :explo, presence: true


end

app/models/category.rb
class Category < ActiveRecord::Base
   has_many :items
   has_many :explos
   has_many :subcategories
   has_attached_file :avatar, :styles => { :medium =>     "300x300#", :thumb => "200x200#" }
   validates_attachment :avatar, content_type: { content_type:     ["image/jpg", "image/jpeg", "image/png"] }
   validates :name, presence: true
   has_many :children, :dependent => :destroy, :class_name => 'Category'
   

end

app/models/explo.rb
class Explo < ActiveRecord::Base
    belongs_to :unit
    has_many :wydanie
    has_many :adoption
    belongs_to :category
    belongs_to :subcategory
    belongs_to :subsubcategory
    
    validates :unit_id, :name, :sn, :polka, :regal, presence: true
    validates :quantity, :numericality => { :greater_than_or_equal_to => 0 }
    
    #has_attached_file :avatar, :styles => { :medium =>     "300x300#", :thumb => "200x200#" }
    #validates_attachment :avatar, content_type: { content_type:     ["image/jpg", "image/jpeg", "image/png"] }

    has_attached_file :avatar, :styles => { :medium => "200x200>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
    validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

    def self.search(search)
      if search
      where("name LIKE ?", "%#{search}%")
    else
      all
    end
    end
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :category
  belongs_to :unit
  belongs_to :location
  has_many :wzs
  validates :unit_id, :location_id, :name, :quantity, :sn, presence: true
  has_attached_file :avatar, :styles => { :medium => "200x200>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/



  def self.search(search)
    where("sn LIKE ?", "%#{search}%")
  end
  
end

app/models/location.rb
class Location < ActiveRecord::Base
     has_many :items
     has_many :wzs
     has_many :accidents
     
     validates :name, :hall, :city, :adress, presence: true
     
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/status.rb
class Status < ActiveRecord::Base
  has_many :accident
  has_many :wz
  has_many :action
end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
     has_many :subsubcategories
     belongs_to :category
     has_many :explos
     
end

app/models/tobuy.rb
class Tobuy < ActiveRecord::Base
  belongs_to :user
end

app/models/unit.rb
class Unit < ActiveRecord::Base
     has_many :explos
     has_many :items
     has_many :adoptions

     validates :name, :unit, presence: true
     

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token
  before_save { email.downcase! }
  has_many :wzs
  has_many :tobuys
  has_many :wydanie
  has_many :accident
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :name, :surname, presence: true
  has_secure_password   
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  
  has_attached_file :avatar, :styles => { :medium => "200x200>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  
  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/models/wydanie.rb
class Wydanie < ActiveRecord::Base
    belongs_to :explo
    belongs_to :user
    
    
    validates :explo_id, :user_id, :quantity, presence: true
    
    
    
end

app/models/wz.rb
class Wz < ActiveRecord::Base
    belongs_to :user
    belongs_to :item
    belongs_to :location
    belongs_to :status
    
    validates :user_id, :item_id, :location_id, :status, :description, :admin_user_id, presence: true
    
end

app/controllers/wydanies_controller.rb
class WydaniesController < ApplicationController

  def new
    @wydanie = Wydanie.new
  end

  def create
    @wydanie = Wydanie.new(wydanie_params)
    @wydanie.user_id = current_user.id
    @wydanie.accept_id = 1
    if @wydanie.save
        #  redirect_to :action => :index
        flash[:success] = "Zamówienie przyjęte do realizacji."
        #redirect_to categories_path
        redirect_to explo_path(@wydanie.explo_id)
    else
      render 'new'
    end
  end
  
  def show
    #@wydanies = Wydanie.where(["sta= ?", @subcategory.id]) 
    @wydanie = Wydanie.find(params[:id])
  end
  
  def index
    @wydanies = Wydanie.all.order('created_at DESC')
  end
  
  def edit
    @wydanie = Wydanie.find(params[:id])
  end
  
  def update
     @wydanie = Wydanie.find(params[:id])
     @wydanie.accept_user = current_user.name + " " + current_user.surname
     if @wydanie.update_attributes(wydanie_params)
     if @wydanie.accept_id == 1 
       flash[:success] = "Status zmieniony na oczekujący"
       redirect_to wydanies_path
     end
     if @wydanie.accept_id == 2
       flash[:success] = "Status zmieniony na zaakceptowany"
       redirect_to wydanies_path
     end
     if @wydanie.accept_id == 3
       flash[:success] = "Status zmieniony na odrzucony"
       redirect_to wydanies_path
     end
     if @wydanie.accept_id == 4
       a = Explo.find(@wydanie.explo_id).quantity
       b = @wydanie.quantity
       Explo.find(@wydanie.explo_id).update_column(:quantity, a -b)
       flash[:success] = "Zamówienie przyjęte i wydane"
       redirect_to wydanies_path
     end
     else
       render 'edit'
     end
   end
   
   def accepted
     @wydanies = Wydanie.all.order('created_at DESC')  
   end
   
   def all
     @wydanies = Wydanie.all.order('created_at DESC')     
   end


  private

    def wydanie_params
      params.require(:wydanie).permit(:user_id, :explo_id, :description, :quantity, :accept_id, :accept_user)
    end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/live_helper.rb
module LiveHelper
end

app/helpers/wydanies_helper.rb
module WydaniesHelper
end

app/helpers/wzs_helper.rb
module WzsHelper
end

app/views/wydanies/accepted.html.erb
<% if current_user.admin?%>

<%- model_class = Wydanie -%>
<div class="page-header">
  <h2>Eksploatacja do wydania</h2>
</div>

<table class="table table-striped table-hover">
  <thead>
    <tr class="active">
	  <th>Numer</th>
      <th>Zgłaszający</th>
      <th>Towar</th>
	  <th>SN</th>
	  <th>Ilość</th>
	  <th>Półka</th>
	  <th>Regał</th>
	  <th>Data zgłoszenia</th>
	  <th></th>
    </tr>
  </thead>
  <tbody>
  <% @wydanies.each do |a| %>
    <% if a.accept_id == 2 %>
	  <tr class="active">
	    <td><%= a.id %></td>
	    <td><%= a.user.name + " " + a.user.surname %></td>
	    <td><%= a.explo.name %></td>
	    <td><%= a.explo.sn %></td>
	    <td><%= a.quantity %></td>
	    <td><%= a.explo.polka %></td>
	    <td><%= a.explo.regal %></td>
	    <td><%= a.created_at.strftime("%d %b. %Y") %></td>
		<td><%= link_to "Edytuj", edit_wydany_path(a) %></td>	
	  </tr> 
    <% end %>
  <% end %>
  </tbody>
</table>
<% else %>
  redirect_to root_path
<% end %>

app/views/wydanies/all.html.erb
<% if current_user.admin?%>

<%- model_class = Wydanie -%>
<div class="page-header">
  <h2>Spis wydanych i odrzuconych</h2>
</div>

<table class="table table-striped table-hover">
  <thead>
    <tr class="active">
	  <th>Numer</th>
      <th>Zgłaszający</th>
	  <th>Wydający</th>
      <th>Towar</th>
	  <th>Ilość</th>
	  <th>Akceptacja</th>
	  <th>Data zgłoszenia</th>
	  <th>Data Aktualizacji</th>
    </tr>
  </thead>
  <tbody>
  <% @wydanies.each do |a| %>
    <% if a.accept_id == 4 %>
	<tr class="success">
	  <td><%= a.id %></td>
	  <td><%= a.user.name + " " + a.user.surname %></td>
	  <td><%= a.accept_user %></td>
	  <td><%= a.explo.name %></td>
	  <td><%= a.quantity %></td>
	  <td>Wydane</td>	
	  <td><%= a.created_at.strftime("%d %b. %Y") %></td>
      <td><%= a.updated_at.strftime("%d %b. %Y") %></td>	
    </tr>
	<% end %>
    <% if a.accept_id == 3 %>
	  <tr class="danger">
	    <td><%= a.id %></td>
	    <td><%= a.user.name + " " + a.user.surname %></td>
	    <td><%= a.accept_user %></td>
	    <td><%= a.explo.name %></td>
	    <td><%= a.quantity %></td>
	    <td>Odrzucone</td>	
	    <td><%= a.created_at.strftime("%d %b. %Y") %></td>
	    <td><%= a.updated_at.strftime("%d %b. %Y") %></td>	
	  </tr> 
    <% end %>
  <% end %>
  </tbody>
</table>
<% else %>
  redirect_to root_path
<% end %>

app/views/wydanies/edit.html.erb
<% provide(:title, 'Wydanie') %>
<h2>Akceptacja zamówienia</h2>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
	  
	  <dt><strong>Pobiera</strong></dt>
	  <dd><%= @wydanie.user.name + " " + @wydanie.user.surname %></dd>

	  <dt><strong>Materiał</strong></dt>
	  <dd><%= @wydanie.explo.name %></dd>
	  
	  
    <%= form_for(@wydanie) do |f| %>

	  <%= f.label "Status"%>
	  <%= f.select :accept_id, [ ['Akceptuj', 2], ['Odrzuć', 3], ['Wydaj', 4] ], :prompt => 'Select One' %><br>
	  
      <%= f.label "Ilość" %>
      <%= f.text_field :quantity, class: 'form-control' %>
	  
      <%= f.label "Uwagi" %>
      <%= f.text_field :description, class: 'form-control' %><br>
	  
      <%= f.submit "Akceptuj", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/wydanies/index.html.erb
<%- model_class = Wydanie -%>
<div class="page-header">
  <h2>Zapotrzebowanie eksploatacji</h2>
</div>

<table class="table table-striped table-hover">
  <thead>
    <tr class="active">
	  <th>Numer</th>
      <th>Zgłaszający</th>
	  <th>Wydający</th>
      <th>Towar</th>
	  <th>Ilość</th>
	  <th>Akceptacja</th>
	  <th>Data zgłoszenia</th>
	  <th>Data Aktualizacji</th>
	  <th></th>
    </tr>
  </thead>
  <tbody>
  <% if current_user.admin? %>
  <% @wydanies.each do |a| %>
    <% if a.accept_id == 1 %>
	  <tr class="warning">
	    <td><%= a.id %></td>
	    <td><%= a.user.name + " " + a.user.surname %></td>
	    <td><%= a.accept_user %></td>
	    <td><%= a.explo.name %></td>
	    <td><%= a.quantity %></td>
	    <td>Oczekuje</td>	
	    <td><%= a.created_at.strftime("%d %b. %Y") %></td>
	    <td><%= a.updated_at.strftime("%d %b. %Y") %></td>	
		<td><%= link_to "Więcej", wydany_path(a) %>	<%= link_to "Edytuj", edit_wydany_path(a) %></td>	
	  </tr> 
    <% end %>	
  <% end %>
  </tbody>
</table>
 <% else %>
   <% @wydanies.each do |a| %>
     <% if a.accept_id == 1 %>
	 <% if a.explo.category_id == 1 %>
 	  <tr class="warning">
 	    <td><%= a.id %></td>
 	    <td><%= a.user.name + " " + a.user.surname %></td>
 	    <td><%= a.accept_user %></td>
 	    <td><%= a.explo.name %></td>
 	    <td><%= a.quantity %></td>
 	    <td>Oczekuje</td>	
 	    <td><%= a.created_at.strftime("%d %b. %Y") %></td>
 	    <td><%= a.updated_at.strftime("%d %b. %Y") %></td>	
 		<td><%= link_to "Więcej", wydany_path(a) %>	<%= link_to "Edytuj", edit_wydany_path(a) %></td>	
 	  </tr> 
	  <% end %>
     <% end %>	
   <% end %>
   </tbody>
 </table>
 <% end %>

app/views/wydanies/new.html.erb
<% provide(:title, 'Wydanie') %>
<h2>Zamówienie</h2>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@wydanie) do |f| %>
   	  
	  <%= f.label "Explo" %>
      <%= f.text_field :explo_id, class: 'form-control' %>
	  
      <%= f.label "Ilość" %>
      <%= f.text_field :quantity, class: 'form-control' %>
	  
      <%= f.label "Uwagi" %>
      <%= f.text_field :description, class: 'form-control' %><br>

      <%= f.submit "Zamów", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/wydanies/show.html.erb
<div class="page-header">
  <h1>Wydanie eksploatacji #<%= @wydanie.id%></h1>
</div>

<div class="col-xs-6">
	 <dt><%= link_to "Wróć", (:back) %></dt><dd></dd>
<dl class="dl-horizontal">
  <dt><strong>Zamawiający</strong></dt>
  <dd><%= @wydanie.user.name + " " + @wydanie.user.surname %></dd>
  <dt><strong>Wydający</strong></dt>
  <dd><%= @wydanie.accept_user %></dd>
  <dt><strong>Status</strong></dt>
  
  
  <dd><% if @wydanie.accept_id == 1 %>
       Oczekujący
	 <% end %>
     <% if @wydanie.accept_id == 2 %>
      Zaakceptowane do wydania
	 <% end %>
    <% if @wydanie.accept_id == 3%>
       Odrzucone
     <% end %>
     <% if @wydanie.accept_id == 4%>
	  Wydane
	  <% end %></dd>
  
  <dt><strong>Sn</strong></dt>
  <dd><%= @wydanie.explo.sn %></dd>
  <dt><strong>Ilość zamawiana</strong></dt>
  <dd><%= @wydanie.quantity %> <%= @wydanie.explo.unit.unit %></dd>
  <dt><strong>Ilość w magazynie</strong></dt>
  <dd><%= @wydanie.explo.quantity %> <%= @wydanie.explo.unit.unit %></dd>
  <dt><strong>Regał</strong></dt>
  <dd><%= @wydanie.explo.regal %></dd>  
  <dt><strong>Półka</strong></dt>
  <dd><%= @wydanie.explo.polka %></dd>
  <dt><strong>Data zgłoszenia</strong></dt>
  <dd><%= @wydanie.created_at %></dd>
  <dt><strong>Data aktualizacji</strong></dt>
  <dd><%= @wydanie.updated_at %></dd>
  <dt><strong>Uwagi</strong></dt>
  <dd><%= @wydanie.description %></dd>
  <% if current_user.admin? %>
  <%= link_to "Aktualizuj", edit_wydany_path(@wydanie) %>
  <% end %>
</div>