config/routes.rb
Rails.application.routes.draw do
  resources :tobuys
  get 'sessions/new'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :items
  resources :categories
  resources :explos
  resources :users
  resources :adoptions 
  resources :accidents
  resources :wydanies
  resources :subcategories
  resources :subsubcategories
  resources :statuses
  resources :locations
  resources :units
  resources :wzs
  resources :lives
  resources :actions
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'acc' => 'wydanies#accepted'
  get 'ac' => 'accidents#ac'
  get 'all' => 'wydanies#all'
  
  
  root'home#index'

end

app/models/accident.rb
class Accident < ActiveRecord::Base
  belongs_to :location
  belongs_to :user
  belongs_to :status
  has_many :action

  validates :location_id, presence: true

end

app/models/action.rb
class Action < ActiveRecord::Base
  belongs_to :user
  belongs_to :accident
  belongs_to :status
  
#    validates :description, :status_id, presence: true

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable  

  has_many :wzs

end

app/models/adoption.rb
class Adoption < ActiveRecord::Base
  belongs_to :user
  belongs_to :explo
  belongs_to :unit
  
  validates :quantity, :explo, presence: true


end

app/models/category.rb
class Category < ActiveRecord::Base
   has_many :items
   has_many :explos
   has_many :subcategories
   has_attached_file :avatar, :styles => { :medium =>     "300x300#", :thumb => "200x200#" }
   validates_attachment :avatar, content_type: { content_type:     ["image/jpg", "image/jpeg", "image/png"] }
   validates :name, presence: true
   has_many :children, :dependent => :destroy, :class_name => 'Category'
   

end

app/models/explo.rb
class Explo < ActiveRecord::Base
    belongs_to :unit
    has_many :wydanie
    has_many :adoption
    belongs_to :category
    belongs_to :subcategory
    belongs_to :subsubcategory
    
    validates :unit_id, :name, :sn, :polka, :regal, presence: true
    validates :quantity, :numericality => { :greater_than_or_equal_to => 0 }
    
    #has_attached_file :avatar, :styles => { :medium =>     "300x300#", :thumb => "200x200#" }
    #validates_attachment :avatar, content_type: { content_type:     ["image/jpg", "image/jpeg", "image/png"] }

    has_attached_file :avatar, :styles => { :medium => "200x200>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
    validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

    def self.search(search)
      if search
      where("name LIKE ?", "%#{search}%")
    else
      all
    end
    end
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :category
  belongs_to :unit
  belongs_to :location
  has_many :wzs
  validates :unit_id, :location_id, :name, :quantity, :sn, presence: true
  has_attached_file :avatar, :styles => { :medium => "200x200>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/



  def self.search(search)
    where("sn LIKE ?", "%#{search}%")
  end
  
end

app/models/location.rb
class Location < ActiveRecord::Base
     has_many :items
     has_many :wzs
     has_many :accidents
     
     validates :name, :hall, :city, :adress, presence: true
     
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/status.rb
class Status < ActiveRecord::Base
  has_many :accident
  has_many :wz
  has_many :action
end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
     has_many :subsubcategories
     belongs_to :category
     has_many :explos
     
end

app/models/tobuy.rb
class Tobuy < ActiveRecord::Base
  belongs_to :user
end

app/models/unit.rb
class Unit < ActiveRecord::Base
     has_many :explos
     has_many :items
     has_many :adoptions

     validates :name, :unit, presence: true
     

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token
  before_save { email.downcase! }
  has_many :wzs
  has_many :tobuys
  has_many :wydanie
  has_many :accident
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :name, :surname, presence: true
  has_secure_password   
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  
  has_attached_file :avatar, :styles => { :medium => "200x200>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  
  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/models/wydanie.rb
class Wydanie < ActiveRecord::Base
    belongs_to :explo
    belongs_to :user
    
    
    validates :explo_id, :user_id, :quantity, presence: true
    
    
    
end

app/models/wz.rb
class Wz < ActiveRecord::Base
    belongs_to :user
    belongs_to :item
    belongs_to :location
    belongs_to :status
    
    validates :user_id, :item_id, :location_id, :status, :description, :admin_user_id, presence: true
    
end

app/controllers/explos_controller.rb
class ExplosController < ApplicationController
  helper_method :sort_column, :sort_direction
  
  #<% if current_user.admin? %>
  
  def index
    @explos = Explo.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 5, :page => params[:page])
    # if current_user.admin?
 #    #@explos = Explo.all
 #    #@explos = Explo.search(params[:search])
 #      @explos = Explo.all.order('created_at DESC')
 #       if params[:search]
 #         @explos = Explo.search(params[:search]).order("created_at DESC")
 #       else
 #         @explos = Explo.all.order('created_at DESC')
 #       end
 #     else
 #      redirect_to root_path
 # end
  end
  
  def new
    @explo = Explo.new
  end
  
  def create
    @explo = Explo.new(explo_params)
    @explo.quantity = 0
    if @explo.save
      if @explo.subcategory == nil
      @explo.subcategory_id = @explo.subsubcategory.subcategory_id
      else
      end
      flash[:success] = "Materiał eksploatacyjny dodany!"
      redirect_to new_explo_path
    else
      render 'new'
    end
  end
  
  
  def show
    @explo = Explo.find(params["id"])
    @wydanies = @explo.wydanie.paginate(:page => params[:page], :per_page => 30).order('created_at DESC')
    @adoptions = @explo.adoption.order('created_at DESC')
    @wydanie = Wydanie.new
    @explos = Explo.where(["subcategory_id= ?", @explo.subcategory_id]) 
    @tobuy = Tobuy.new
    @adoption = Adoption.new
  end
  
  def edit
    @explo = Explo.find(params[:id])
  end
  
  def update
    @explo = Explo.find(params[:id])
    if @explo.update_attributes(explo_params)
      # Handle a successful update.
      flash[:success] = "Zdjęcie dodane"
      redirect_to (@explo)
    else
      render 'edit'
    end
  end
  
  private

  def sort_column
      Explo.column_names.include?(params[:sort]) ? params[:sort] : "name"
    end
  
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
    def explo_params
      params.require(:explo).permit(:name, :sn, :regal, :polka, :quantity, :description, :unit_id, :category_id, :subcategory_id, :subsubcategory_id, :avatar)
    end
end

app/helpers/explos_helper.rb
module ExplosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/live_helper.rb
module LiveHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/wzs_helper.rb
module WzsHelper
end

app/views/explos/_explos.html.erb
<table class="table table-striped table-hover">
  <thead>
    <tr class="active">
      <th><%= sortable "name", "Nazwa" %></th>
      <th>SN</th>
      <th>Ilość</th>
	  <th>Jednostka</th>
	  <th><%= sortable "regal", "Regał"%></th>
	  <th>Półka</th>
      <th>Uwagi</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @explos.each do |explo| %>
      <tr>
        <td><%= explo.name.truncate(30) %></td>
        <td><%= explo.sn.truncate(20) %></td>
        <td><%= explo.quantity %></td>
		<td><%= explo.unit.name %></td>
		<td><%= explo.regal %></td>
		<td><%= explo.polka %></td>
        <td><%= explo.description.truncate(10) %></td>
		<td style="width:80px"> <%= link_to "Więcej", explo_path(explo) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @explos%>

app/views/explos/_form.html.erb
<% provide(:title, 'Nowa esploatacja') %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@explo) do |f| %>

      <%#= f.label "Kategoria" %><br>
	  <%#= f.collection_select :category_id, Category.all, :id, :name, prompt: true %><br>
	  
      <%= f.label "Kategoria" %><br>
	  <%= f.collection_select :subcategory_id, Subcategory.all, :id, :name, prompt: true %><br>
	  
      <%= f.label "Podkategoria" %><br>
	  <%= f.collection_select :subsubcategory_id, Subsubcategory.all, :id, :name, prompt: true %><br>
	  
      <%= f.label "Nazwa" %>
      <%= f.text_field :name, class: 'form-control' %>
	  
      <%= f.label "Ilość dodać przez przyjęcie towaru na magazyn" %><br>
      <%#= f.number_field :quantity, class: 'form-control' %>
	  
      <%= f.label "Jednostka" %><br>
	  <%= f.collection_select :unit_id, Unit.all, :id, :name, prompt: true %><br>
	  
      <%= f.label "SN" %>
      <%= f.text_field :sn, class: 'form-control' %>
	  
      <%= f.label "Regał" %>
      <%= f.text_field :regal, class: 'form-control' %>
	  
      <%= f.label "Półka" %>
      <%= f.text_field :polka, class: 'form-control' %>
	  
      <%= f.label "Uwagi" %>
      <%= f.text_area :description, class: 'form-control' %><br>

      <%= f.submit "Dodaj/Zmień", class: "btn btn-primary" %><br>
    <% end %>
  </div>
</div>

app/views/explos/edit.html.erb
<h2>Dodanie zdjęcia</h2>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@explo) do |f| %>
	  
 	 	<div class="form-group">
        <%= f.label :avatar, class: 'col-sm-2 control-label'  %>
        <div class="col-sm-6">
            <%= f.file_field :avatar %>
        </div>
	  </div>
      <%= f.submit "Aktualizuj", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

	
	

app/views/explos/index.html.erb
<%- model_class = Explo -%>
<div class="page-header">
  <h1>Spis materiałów eksploatacyjnych</h1>
</div>

<!-- <%= form_tag(explos_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], placeholder: "Szukaj SN" %>
<%= submit_tag "Szukaj" %>
<% end %> -->

<%= form_tag explos_path, :method => 'get', :id => "explos_search" do %>
  <%= hidden_field_tag :direction, params[:direction] %>
  <%= hidden_field_tag :sort, params[:sort] %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<br>
<div id="explos"><%= render "explos"%></div>
<!-- <table class="table table-striped table-hover">
  <thead>
    <tr class="active">
      <th><%= sortable "name", "Nazwa" %></th>
      <th>SN</th>
      <th>Ilość</th>
	  <th>Jednostka</th>
	  <th><%= sortable "regal", "Regał"%></th>
	  <th>Półka</th>
      <th>Uwagi</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @explos.each do |explo| %>
      <tr>
        <td><%= explo.name.truncate(30) %></td>
        <td><%= explo.sn.truncate(20) %></td>
        <td><%= explo.quantity %></td>
		<td><%= explo.unit.name %></td>
		<td><%= explo.regal %></td>
		<td><%= explo.polka %></td>
        <td><%= explo.description.truncate(10) %></td>
		<td style="width:80px"> <%= link_to image_tag("http://icons.iconarchive.com/icons/double-j-design/super-mono-3d/96/button-round-play-icon.png",:width=>30,:height=>30, :border=>0), explo_path(explo) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @explos%> -->

  <%= link_to image_tag("http://icons.iconarchive.com/icons/double-j-design/super-mono-3d/96/button-round-fast-backward-icon.png",:width=>50,:height=>50, :border=>0), root_path %> 

app/views/explos/new.html.erb
<br>
<%= render 'form' %>

app/views/explos/show.html.erb
<div class="page-header">
  <h1>Eksploatacja</h1>
</div>

    <div class="row">
      <div class="col-xs-8 col-sm-6">
<div class="col-xs-4 col-sm-6">
<dl class="dl-horizontal">
  <dt><% if @explo.category %>
    <%= link_to "Wróć do #{@explo.category.name}", subcategory_path(@explo.category) %>
  <% end %>
  <% if @explo.subcategory %>
    <%= link_to "Wróć do #{@explo.subcategory.name}", subcategory_path(@explo.subcategory) %>
  <% end %>
  <% if @explo.subsubcategory %>
    <%= link_to "Wróć do #{@explo.subsubcategory.name}", subsubcategory_path(@explo.subsubcategory) %>
  <% end %></dt>
  <dd></dd>
  
  
  <dt><strong>Nazwa</strong></dt>
  <dd><%= @explo.name %></dd>
  <% if current_user.admin?%> 
    <dt><strong>Sn</strong></dt>
    <dd><%= @explo.sn %></dd>
    <dt><strong>Regał</strong></dt>
    <dd><%= @explo.regal %></dd>
    <dt><strong>Półka</strong></dt>
    <dd><%= @explo.polka %></dd>
    <dt><strong>Ilość</strong></dt>
    <dd><%= @explo.quantity %></dd>
    <dt><strong>Uwagi</strong></dt>
    <dd><%= @explo.description %></dd>
    <dt><strong>Kategoria</strong></dt>
    <dd><%= @explo.unit.name %></dd>
  <% end %>
  <br>
 
  
</div>
<div class="col-xs-4 col-sm-6">
	<dt><%= link_to "Dodaj zdjęcie", edit_explo_path(@explo) %></dt>
	<% if @explo.avatar? %>
 <%= image_tag(@explo.avatar.url(:medium)) %>
 <% end %>
</div>
	
</div>
  <div class="col-xs-4 col-sm-6">
	  <div class="col-xs-2 col-sm-6">
  <% if @explo.quantity >= 0 %>
	<dt><strong>Zamówienie.</strong></dt>
    <%= form_for(@wydanie) do |f| %>
	
	  <%= f.hidden_field :explo_id, :value => @explo.id %><br>
	  
      <%= f.label "Ilość" %>
      <%= f.text_field :quantity, class: 'form-control' %>
	  
      <%= f.label "Uwagi" %>
      <%= f.text_field :description, class: 'form-control' %><br>

      <%= f.submit "Zamów", class: "btn btn-primary" %>
	  
    <% end %>
	
  <% else %>
    <dt><strong>Brak materiałów na stanie, dodaj do listy zakupów.</strong></dt>
    <%= form_for(@tobuy) do |f| %>
	
	<%= f.hidden_field :name, :value => @explo.name %>
	
	<%= f.hidden_field :quantity, :value => 0 %><br>

    <%= f.label "Uwagi" %>
    <%= f.text_field :desctiption, class: 'form-control' %><br>
	
	<%= f.submit "Dodaj do listy zakupów", class: "btn btn-primary" %>

	<% end %>
	
  <% end %>
</div>
<div class="col-xs-2 col-sm-6">
	<% if current_user.admin?%>
   <dt><strong>Wprowadź na stan.</strong></dt>
  <%= form_for(@adoption) do |f| %>

    <%= f.hidden_field :explo_id, :value => @explo.id %><br>
  
    <%= f.label "Ilość" %>
    <%= f.text_field :quantity, class: 'form-control' %>
  
    <%= f.label "Uwagi" %>
    <%= f.text_field :description, class: 'form-control' %><br>

    <%= f.submit "Wprowadź na stan", class: "btn btn-primary" %>
  
  <% end %>
  <% end %>
</div>
</div>
</div>


  <% if current_user.admin?%>

  <br>

<center>
    <div class="row">
      <div class="col-xs-8 col-sm-6">
		  <strong>Wydane: </strong>
		  <%= Wydanie.where("explo_id = ? and accept_id = ?", @explo.id, "4").sum(:quantity)%>
		  <%#= @wydanies.where(@wydanies.each do |w| w.accept_id == 4).sum(:quantity)%>
		  <table class="table table-striped table-hover">
		    <thead>
		      <tr class="active">
				<th>ID</th>
		        <th>Ilość</th>
		        <th>Kto</th>
				<th>Data wydania</th>
		      </tr>
		    </thead>
		   <tbody>
		    <% @wydanies.each do |wydanie| %>
			<% if wydanie.accept_id == 4%>
		      <tr>
				<td><%= wydanie.id %></td>
		        <td>-<%= wydanie.quantity %></td>
		        <td><%= wydanie.user.name %></td>
				<td><%= wydanie.created_at.strftime("%d %b. %Y") %></td>
				      </tr>
		    <% end %>

			<% end %>
		  </tbody>
		</table>
      </div>
      <div class="col-xs-4 col-sm-6">
	     <strong>Przyjęte: </strong>
		 <%= Adoption.where(explo: @explo.id).sum(:quantity)%>
	     <table class="table table-striped table-hover">
	       <thead>
	         <tr class="active">
	   		<th>ID</th>
	           <th>Ilość</th>
	           <th>Kto</th>
	   		<th>Data wydania</th>
	         </tr>
	       </thead>
	      <tbody>
	       <% @adoptions.each do |adoption| %>
	         <tr>
	   		<td><%= adoption.id %></td>
	   		<td><%= adoption.quantity %></td>
	   		<td></td>
	   		<td><%= adoption.created_at.strftime("%d %b. %Y") %></td>

	   		      </tr>
	       <% end %>
	     </tbody>
	   </table>
      </div>
    </div>
</center>
<% end %>
<br>
	  <table class="table table-striped table-hover">
  	    <thead>
    	  <tr class="active">
      	    <th>Nazwa</th>
      	  	<th>SN</th>
	  	  	<% if current_user.admin?%> 
      	  	  <th>Ilość</th>
	  		  <th>Jednostka</th>
	  		  <th>Regał</th>
	  		  <th>Półka</th>
        	  <th>Uwagi</th>
	  		<% end %>
      	    <th></th>
    	  </tr>
  		</thead>
  	    <tbody>
    	  <% @explos.each do |explo| %>
      		<tr>
        	  <td><%= explo.name.truncate(30) %></td>
        	  <td><%= explo.sn.truncate(20) %></td>
	    	  <% if current_user.admin?%> 
           	    <td><%= explo.quantity %></td>
		  	  	<td><%= explo.unit.unit %></td>
		 	   	<td><%= explo.regal %></td>
		  	  	<td><%= explo.polka %></td>
          	  	<td><%= explo.description.truncate(20) %></td>
			  <% end %>
			  <td style="width:80px"> <%= link_to image_tag("http://icons.iconarchive.com/icons/double-j-design/super-mono-3d/96/button-round-play-icon.png",:width=>30,:height=>30, :border=>0), explo_path(explo) %></td>
     	 	</tr>
    	  <% end %>
  		</tbody>
	  </table>