config/routes.rb
Rails.application.routes.draw do
  resources :tobuys
  get 'sessions/new'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :items
  resources :categories
  resources :explos
  resources :users
  resources :adoptions 
  resources :accidents
  resources :wydanies
  resources :subcategories
  resources :subsubcategories
  resources :statuses
  resources :locations
  resources :units
  resources :wzs
  resources :lives
  resources :actions
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'acc' => 'wydanies#accepted'
  get 'ac' => 'accidents#ac'
  get 'all' => 'wydanies#all'
  
  
  root'home#index'

end

app/models/accident.rb
class Accident < ActiveRecord::Base
  belongs_to :location
  belongs_to :user
  belongs_to :status
  has_many :action

  validates :location_id, presence: true

end

app/models/action.rb
class Action < ActiveRecord::Base
  belongs_to :user
  belongs_to :accident
  belongs_to :status
  
#    validates :description, :status_id, presence: true

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable  

  has_many :wzs

end

app/models/adoption.rb
class Adoption < ActiveRecord::Base
  belongs_to :user
  belongs_to :explo
  belongs_to :unit
  
  validates :quantity, :explo, presence: true


end

app/models/category.rb
class Category < ActiveRecord::Base
   has_many :items
   has_many :explos
   has_many :subcategories
   has_attached_file :avatar, :styles => { :medium =>     "300x300#", :thumb => "200x200#" }
   validates_attachment :avatar, content_type: { content_type:     ["image/jpg", "image/jpeg", "image/png"] }
   validates :name, presence: true
   has_many :children, :dependent => :destroy, :class_name => 'Category'
   

end

app/models/explo.rb
class Explo < ActiveRecord::Base
    belongs_to :unit
    has_many :wydanie
    has_many :adoption
    belongs_to :category
    belongs_to :subcategory
    belongs_to :subsubcategory
    
    validates :unit_id, :name, :sn, :polka, :regal, presence: true
    validates :quantity, :numericality => { :greater_than_or_equal_to => 0 }
    
    #has_attached_file :avatar, :styles => { :medium =>     "300x300#", :thumb => "200x200#" }
    #validates_attachment :avatar, content_type: { content_type:     ["image/jpg", "image/jpeg", "image/png"] }

    has_attached_file :avatar, :styles => { :medium => "200x200>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
    validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

    def self.search(search)
      if search
      where("name LIKE ?", "%#{search}%")
    else
      all
    end
    end
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :category
  belongs_to :unit
  belongs_to :location
  has_many :wzs
  validates :unit_id, :location_id, :name, :quantity, :sn, presence: true
  has_attached_file :avatar, :styles => { :medium => "200x200>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/



  def self.search(search)
    where("sn LIKE ?", "%#{search}%")
  end
  
end

app/models/location.rb
class Location < ActiveRecord::Base
     has_many :items
     has_many :wzs
     has_many :accidents
     
     validates :name, :hall, :city, :adress, presence: true
     
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/status.rb
class Status < ActiveRecord::Base
  has_many :accident
  has_many :wz
  has_many :action
end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
     has_many :subsubcategories
     belongs_to :category
     has_many :explos
     
end

app/models/tobuy.rb
class Tobuy < ActiveRecord::Base
  belongs_to :user
end

app/models/unit.rb
class Unit < ActiveRecord::Base
     has_many :explos
     has_many :items
     has_many :adoptions

     validates :name, :unit, presence: true
     

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token
  before_save { email.downcase! }
  has_many :wzs
  has_many :tobuys
  has_many :wydanie
  has_many :accident
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :name, :surname, presence: true
  has_secure_password   
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  
  has_attached_file :avatar, :styles => { :medium => "200x200>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  
  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/models/wydanie.rb
class Wydanie < ActiveRecord::Base
    belongs_to :explo
    belongs_to :user
    
    
    validates :explo_id, :user_id, :quantity, presence: true
    
    
    
end

app/models/wz.rb
class Wz < ActiveRecord::Base
    belongs_to :user
    belongs_to :item
    belongs_to :location
    belongs_to :status
    
    validates :user_id, :item_id, :location_id, :status, :description, :admin_user_id, presence: true
    
end

app/controllers/accidents_controller.rb
class AccidentsController < ApplicationController

  def new
    @accident = Accident.new
    @locations = Location.all
  end

  def create
    @accident = Accident.new(accident_params)
    @accident.user_id = current_user.id
    @accident.status_id = 1
    @accident.repman_id = "Oczekuje"
    if @accident.save
        #  redirect_to :action => :index
        flash[:success] = "Awaria zgłoszona"
        redirect_to @accident
      # Handle a successful save.
    else
      render 'new'
    end
  end
  
  def show
    @accident = Accident.find(params[:id])
    @action = Action.new
    @actions = Action.all
  end
  
  def ac
    @accidents = Accident.all
  end
  
  def index
    @accidents = Accident.all.order('created_at DESC')
  end
  
  def edit
    @accident = Accident.find(params[:id])
  end
  
  def update
     @accident = Accident.find(params[:id])
     @accident.repman_id = current_user.name + " " + current_user.surname
     if @accident.update_attributes(accident_params)
       # Handle a successful update.
       flash[:success] = "Awazja zaktualizowana."
       redirect_to accidents_path
     else
       render 'edit'
     end
   end
  
  private

    def accident_params
      params.require(:accident).permit(:user_id, :location_id, :desctiption, :status_id, :mode)
    end
  
  

end

app/helpers/accidents_helper.rb
module AccidentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/live_helper.rb
module LiveHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/wzs_helper.rb
module WzsHelper
end

app/views/accidents/ac.html.erb
<% if current_user.admin?%>

<%- model_class = Accident -%>
<div class="page-header">
  <h2>Spis awarii wykonanych</h2>
</div>

<table class="table table-striped table-hover">
  <thead>
    <tr class="active">
	  <th>Numer</th>
      <th>Zgłaszający</th>
	  <th>Naprawiający</th>
      <th>Lokalizacja</th>
      <th>Status</th>
	  <th>Tryb</th>
	  <th>Opis</th>
	  <th>Data zgłoszenia</th>
	  <th>Data Aktualizacji</th>
	  <th></th>
    </tr>
  </thead>
  <tbody>
  <% @accidents.each do |a| %>
    <tr>
			<% if a.status.name == "Zrobione" %>
	  <td><%= a.id %></td>
	  <td><%= a.user.name + " " + a.user.surname %></td>
	  <td><%= a.repman_id %></td>
	  <td><%= a.location.name %></td>
	  <td><%= a.status.name %></td>
	  <td><%= a.mode %></td>
      <td><%= a.desctiption.truncate(15) %></td>	
	  <td><%= a.created_at.strftime("%d %b. %Y") %></td>
      <td><%= a.updated_at.strftime("%d %b. %Y") %></td>	
	  <td><%= link_to "Więcej", accident_path(a) %></td>
    </tr>
	<% end %>
    <% end %>
  </tbody>
</table>










<% else %>
  redirect_to root_path
<% end %>

app/views/accidents/edit.html.erb
<% provide(:title, "New accident") %>
<h2>Aktualizacja awarii</h2>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@accident) do |f| %>
	  
      <%= f.label "Status" %>
	  <%= f.collection_select :status_id, Status.all, :id, :name, prompt: true %><br>
	  
      <%= f.submit "Aktualizuj", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/accidents/index.html.erb
<% if current_user.admin?%>

<%- model_class = Accident -%>
<div class="page-header">
  <h2>Spis awarii</h2>
</div>

<table class="table table-striped table-hover">
  <thead>
    <tr class="active">
	  <th>Numer</th>
      <th>Zgłaszający</th>
	  <th>Naprawiający</th>
      <th>Lokalizacja</th>
      <th>Status</th>
	  <th>Tryb</th>
	  <th>Opis</th>
	  <th>Data zgłoszenia</th>
	  <th>Data Aktualizacji</th>
	  <th></th>
    </tr>
  </thead>
  <tbody>
  <% @accidents.each do |a| %>
      <% if a.status.name == "Zrobione" %>
      <% else %>
	  <% if a.mode == "Pilne" %>
	    <tr class="danger">
	  <td><%= a.id %></td>
	  <td><%= a.user.name + " " + a.user.surname %></td>
	  <td><%= a.repman_id %></td>
	  <td><%= a.location.name %></td>
	  <td><%= a.status.name %></td>
	  <td><%= a.mode %></td>
      <td><%= a.desctiption.truncate(15) %></td>	
	  <td><%= a.created_at.strftime("%d %b. %Y") %></td>
      <td><%= a.updated_at.strftime("%d %b. %Y") %></td>	
	  <td><%= link_to "Więcej", accident_path(a) %></td>
    </tr>
	<% else %>
    <tr>
	  <td><%= a.id %></td>
	  <td><%= a.user.name + " " + a.user.surname %></td>
	  <td><%= a.repman_id %></td>
	  <td><%= a.location.name %></td>
	  <td><%= a.status.name %></td>
	  <td><%= a.mode %></td>
      <td><%= a.desctiption.truncate(15) %></td>	
	  <td><%= a.created_at.strftime("%d %b. %Y") %></td>
      <td><%= a.updated_at.strftime("%d %b. %Y") %></td>	
	  <td><%= link_to "Więcej", accident_path(a) %></td>
    </tr>
	<% end %>
	<% end %>
	<% end %>
  </tbody>
</table>










<% else %>
  redirect_to root_path
<% end %>

app/views/accidents/new.html.erb
<% provide(:title, "New accident") %>
<h2>Zgłoszenie awarii</h2>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@accident) do |f| %>

      <%= f.label "Tryb" %>
	  <%= f.select(:mode, [["Standard"], ["Pilne"], ["Przy okazji"]]) %><br>
	  
      <%= f.label "Lokalizacja" %>
	  <%= f.collection_select :location_id, Location.all, :id, :name, prompt: true %><br>

      <%= f.label "Opis awarii" %>
      <%= f.text_area :desctiption, class: 'form-control' %><br>
	  
      <%= f.submit "Zgłoś", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/accidents/show.html.erb
<div class="page-header">
  <h2>Opis awarii</h2>
</div>
<dt><%= link_to 'Back', :back %></dt><dd></dd>

    <div class="row">
      <div class="col-xs-3 col-sm-6">
		  
<dl class="dl-horizontal">
  <dt><strong>Zgłaszający</strong></dt>
  <dd><%= @accident.user.name + " " + @accident.user.surname %></dd>
  <dt><strong>Naprawiający</strong></dt>
  <dd><%= @accident.repman_id %></dd>
  <dt><strong>Status</strong></dt>
  <dd><%= @accident.status.name %></dd>
  <dt><strong>Tryb</strong></dt>
  <dd><%= @accident.mode %></dd>
  <dt><strong>Lokalizacja</strong></dt>
  <dd><%= @accident.location.name %></dd>
  <dt><strong>Data zgłoszenia</strong></dt>
  <dd><%= @accident.created_at.strftime("%d %b. %Y") %></dd>
  <dt><strong>Data aktualizacji</strong></dt>
  <dd><%= @accident.updated_at.strftime("%d %b. %Y") %></dd>
  <dt><strong>Opis</strong></dt>
  <dd><%= @accident.desctiption %></dd>

</dl>
</div>
      <div class="col-xs-9 col-sm-6">
		  <% if current_user.admin? %>
		  <b><i>Wpis działań</b></i>
	      <%= form_for(@action, as: :foo) do |f| %>
	
	  	 	<%= f.hidden_field :accident_id, :value => @accident.id %>
	  	    <%= f.hidden_field :user_id, :value => current_user.id %>
		    
	        <%= f.label "Status" %>
	        <%= f.collection_select :status_id, Status.all, :id, :name, {:selected => "#{@accident.status_id}"}, prompt: true %><br>
	  
	        <%= f.label "Uwagi" %>
	        <%= f.text_area :description, class: 'form-control' %><br>

	        <%= f.submit "Wpisz", class: "btn btn-primary" %>
	  
	      <% end %>
		  
		  <% end %>
</div>
</div>

    <div class="row">
		<b>Historia awarii</b>
  	  <table class="table table-striped table-hover">
    	    <thead>
      	  <tr class="active">
        	    <th>Użytkownik</th>
        	  	<th>Status</th>
			  <th>Data</th>
          	  <th>Uwagi</th>
			  <th></th>
      	  </tr>
    		</thead>
    	    <tbody>

      	  <% @actions.each do |a| %>
		  <% if a.accident_id == @accident.id %>
        		<tr>
          	  	  <td><%= a.user.name + " " + a.user.surname %></td>
             	  <td><%= a.status.name %></td>
				  <td><%= a.created_at %></td>
            	  	<td><%= a.description.truncate(20) %></td>
					<td><%= link_to "Więcej", action_path(a)%>

       	 	</tr>
      	  <% end %>
		  <% end %>
    		</tbody>
  	  </table>
	</div>



        
		
  	  