config/routes.rb
Rails.application.routes.draw do
  resources :tobuys
  get 'sessions/new'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :items
  resources :categories
  resources :explos
  resources :users
  resources :adoptions 
  resources :accidents
  resources :wydanies
  resources :subcategories
  resources :subsubcategories
  resources :statuses
  resources :locations
  resources :units
  resources :wzs
  resources :lives
  resources :actions
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'acc' => 'wydanies#accepted'
  get 'ac' => 'accidents#ac'
  get 'all' => 'wydanies#all'
  
  
  root'home#index'

end

app/models/accident.rb
class Accident < ActiveRecord::Base
  belongs_to :location
  belongs_to :user
  belongs_to :status
  has_many :action

  validates :location_id, presence: true

end

app/models/action.rb
class Action < ActiveRecord::Base
  belongs_to :user
  belongs_to :accident
  belongs_to :status
  
#    validates :description, :status_id, presence: true

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable  

  has_many :wzs

end

app/models/adoption.rb
class Adoption < ActiveRecord::Base
  belongs_to :user
  belongs_to :explo
  belongs_to :unit
  
  validates :quantity, :explo, presence: true


end

app/models/category.rb
class Category < ActiveRecord::Base
   has_many :items
   has_many :explos
   has_many :subcategories
   has_attached_file :avatar, :styles => { :medium =>     "300x300#", :thumb => "200x200#" }
   validates_attachment :avatar, content_type: { content_type:     ["image/jpg", "image/jpeg", "image/png"] }
   validates :name, presence: true
   has_many :children, :dependent => :destroy, :class_name => 'Category'
   

end

app/models/explo.rb
class Explo < ActiveRecord::Base
    belongs_to :unit
    has_many :wydanie
    has_many :adoption
    belongs_to :category
    belongs_to :subcategory
    belongs_to :subsubcategory
    
    validates :unit_id, :name, :sn, :polka, :regal, presence: true
    validates :quantity, :numericality => { :greater_than_or_equal_to => 0 }
    
    #has_attached_file :avatar, :styles => { :medium =>     "300x300#", :thumb => "200x200#" }
    #validates_attachment :avatar, content_type: { content_type:     ["image/jpg", "image/jpeg", "image/png"] }

    has_attached_file :avatar, :styles => { :medium => "200x200>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
    validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

    def self.search(search)
      if search
      where("name LIKE ?", "%#{search}%")
    else
      all
    end
    end
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :category
  belongs_to :unit
  belongs_to :location
  has_many :wzs
  validates :unit_id, :location_id, :name, :quantity, :sn, presence: true
  has_attached_file :avatar, :styles => { :medium => "200x200>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/



  def self.search(search)
    where("sn LIKE ?", "%#{search}%")
  end
  
end

app/models/location.rb
class Location < ActiveRecord::Base
     has_many :items
     has_many :wzs
     has_many :accidents
     
     validates :name, :hall, :city, :adress, presence: true
     
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/status.rb
class Status < ActiveRecord::Base
  has_many :accident
  has_many :wz
  has_many :action
end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
     has_many :subsubcategories
     belongs_to :category
     has_many :explos
     
end

app/models/tobuy.rb
class Tobuy < ActiveRecord::Base
  belongs_to :user
end

app/models/unit.rb
class Unit < ActiveRecord::Base
     has_many :explos
     has_many :items
     has_many :adoptions

     validates :name, :unit, presence: true
     

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token
  before_save { email.downcase! }
  has_many :wzs
  has_many :tobuys
  has_many :wydanie
  has_many :accident
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :name, :surname, presence: true
  has_secure_password   
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  
  has_attached_file :avatar, :styles => { :medium => "200x200>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  
  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/models/wydanie.rb
class Wydanie < ActiveRecord::Base
    belongs_to :explo
    belongs_to :user
    
    
    validates :explo_id, :user_id, :quantity, presence: true
    
    
    
end

app/models/wz.rb
class Wz < ActiveRecord::Base
    belongs_to :user
    belongs_to :item
    belongs_to :location
    belongs_to :status
    
    validates :user_id, :item_id, :location_id, :status, :description, :admin_user_id, presence: true
    
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_filter :check_logged_in
  def index
    @categories = Category.all
    @subcategories = Subcategory.all
    @subsubcategories = Subsubcategory.all 
    @explos = Explo.all
    # @category_id = Category.find_by(name: params[:category])
  #   @gigs = Gig.where(category_id: @category_id).order("created_at DESC")
  #   @subcategory_id = Subcategory.find_by(name: params[:subcategory])
  #   @gigs = Gig.where(subcategory_id: @subcategory_id).order("created_at DESC")
    
  end
  
  def show
    @category = Category.find(params["id"])
  end
  
  def new
    @category = Category.new
  end
  
  
  def create
    @category = Category.new(category_params)
    if @category.save
        #@explo.subsubcategory.subcategory
        flash[:success] = "Kategoria dodana!"
        redirect_to categories_path
        #  redirect_to :action => :index
        #flash[:success] = "Materiał eksploatacyjny dodany!"
        #render 'new'
      # Handle a successful save.
    else
      render 'new'
    end
  end
  


  private
  def check_logged_in 
    authenticate_or_request_with_http_basic("Home") do |username, password|
    username == "admin" && password == "admin"
    end
  end
  
  def category_params
    params.require(:category).permit(:name, :desctiption)
  end
    



end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/live_helper.rb
module LiveHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/wzs_helper.rb
module WzsHelper
end

app/views/categories/_form.html.erb
<% provide(:title, 'Nowa kategoria') %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@category) do |f| %>
  
      <%= f.label "Nazwa" %>
      <%= f.text_field :name, class: 'form-control' %>
	  
      <%= f.label "Uwagi" %>
      <%= f.text_area :description, class: 'form-control' %><br>

      <%= f.submit "Dodaj/Zmień", class: "btn btn-primary" %><br>
    <% end %>
  </div>
</div>

app/views/categories/index.html.erb
<div class="page-header">
  <h2>Kategorie</h2>
    <%= link_to "Wróć", root_path %>
</div>

<div class="col-xs-4 col-sm-6">
  <% @categories.each do |category| %>
    <dl class="dl-horizontal">
      <dt><%= category.name %></dt>
      <% @subcategories.each do |c| %>
        <% if c.category_id == category.id %>
		  <%# if Explo.where("subcategory_id= ?", c.id ).count(:id) != 0%>
		    <dd><%=link_to c.name, subcategory_path(c) %> (<%= Explo.where("subcategory_id= ?", c.id ).count(:id)%>)</dd>
 	  	    <% @subsubcategories.each do |sc| %>
	  		  <% if sc.subcategory_id == c.id %>
			    <%# if Explo.where("subsubcategory_id= ?", sc.id ).count(:id) != 0%>
	   	 	      <dd><li><p><%=link_to sc.name, subsubcategory_path(sc) %>  (<%= Explo.where("subsubcategory_id= ?", sc.id ).count(:id)%>)</p></li></dd>
				<%# end %>
	  	  	  <% end %>
			<%# end %>
	  	  <% end %>
    	<% end %>
      <% end %>
    </dl>
  <% end %>
  <br>

  
</div>
<div class="col-xs-4 col-sm-6">
  <dl class="dl-horizontal">
    <dt>Ilość ilości</dt>
	<dd><%= @explos.sum(:quantity)%></dd>
	<dt>Ilość pozycji</dt>
	<dd><%= @explos.count(:id)%></dd>
	<% if current_user.admin? %>
	  <dt><%= link_to "Nowa kategoria", new_category_path %></dt>
	  <dt><%= link_to "Nowa podkategoria", new_subcategory_path %></dt>
	<% end %>
  </dl>
</div>

app/views/categories/new.html.erb
<br>
<%= render 'form' %>

app/views/categories/show.html.erb
<div class="page-header">
  <h1>Item</h1>
</div>

  <% @category.each do |category| %>
    <tr>
		<td><%= category.id %></td>
      <td><%=link_to category.name, category_path(category) %></td>
      <td><%= category.description%></td>
	  <td style="width:80px"> <%= link_to image_tag("http://icons.iconarchive.com/icons/double-j-design/super-mono-3d/96/button-round-play-icon.png",:width=>30,:height=>30, :border=>0), category_path(category) %></td>

    </tr>
<% end %>